name: Notify Changes

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_CHANNEL: PF-Henry | Grupo 06  # Puedes cambiar 'general' al nombre de tu canal de Slack

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify changes on Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Hey, hay cambios en el repositorio. Por favor, actualiza tu copia local.","channel":"'"$SLACK_CHANNEL"'"}' \
          $SLACK_WEBHOOK

